name: Configure  AWS Credentials
uses: aws-actions/configure-aws-credentials@v1
with:
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: eu-west-1

 uses: hashicorp/setup-terraform@v1

 -name: Infra initiate
 run: |
    cd infra
    terraform init

 
 -name: terraform apply
 if: ${{ inputs.action == 'apply'  }}
 run: terraform apply -auto-approve
 -name: terraform plan
 if: ${{ inputs.action == 'plan'  }}
 run: terraform plan
 -name: terraform destroy
 if: ${{ inputs.action == 'destroy'  }}
 if: ${{ inputs.action == 'destroy'  }}
 run: terraform destroy -auto-approve